#!/bin/bash
TAG=${1:-}

if [ -z "$TAG" ]; then
    echo "Usage: $0 <version>"
    echo "  Example: $0 2.0.10"
    exit 1
fi

echo "Building $TAG"
docker build -t shpd-build -f Dockerfile.build .
docker run -ti --rm -e TAG=$TAG -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/go/src/github.com/shipyard/shpd -w /go/src/github.com/shipyard/shpd/shpd shpd-build make TAG=$TAG image
